/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface EIP712Interface extends utils.Interface {
  functions: {
    "getChainId()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getChainId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getChainId", data: BytesLike): Result;

  events: {};
}

export interface EIP712 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EIP712Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getChainId(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getChainId(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getChainId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getChainId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
