/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IACLInterface extends utils.Interface {
  functions: {
    "addPermission(bytes32,bytes32,uint8)": FunctionFragment;
    "getPermissions(bytes32,bytes32)": FunctionFragment;
    "hasPermission(address,address,uint8)": FunctionFragment;
    "removePermission(bytes32,bytes32,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addPermission",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermissions",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPermission",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removePermission",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePermission",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IACL extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IACLInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addPermission(
      entity: BytesLike,
      app: BytesLike,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPermissions(
      entity: BytesLike,
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    hasPermission(
      entityAddress: string,
      appAddress: string,
      permissionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removePermission(
      entity: BytesLike,
      app: BytesLike,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addPermission(
    entity: BytesLike,
    app: BytesLike,
    permission: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPermissions(
    entity: BytesLike,
    app: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  hasPermission(
    entityAddress: string,
    appAddress: string,
    permissionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removePermission(
    entity: BytesLike,
    app: BytesLike,
    permission: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addPermission(
      entity: BytesLike,
      app: BytesLike,
      permission: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getPermissions(
      entity: BytesLike,
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    hasPermission(
      entityAddress: string,
      appAddress: string,
      permissionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removePermission(
      entity: BytesLike,
      app: BytesLike,
      permission: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addPermission(
      entity: BytesLike,
      app: BytesLike,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPermissions(
      entity: BytesLike,
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasPermission(
      entityAddress: string,
      appAddress: string,
      permissionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removePermission(
      entity: BytesLike,
      app: BytesLike,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPermission(
      entity: BytesLike,
      app: BytesLike,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPermissions(
      entity: BytesLike,
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasPermission(
      entityAddress: string,
      appAddress: string,
      permissionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removePermission(
      entity: BytesLike,
      app: BytesLike,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
