/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IAppManagerInterface extends utils.Interface {
  functions: {
    "connectApp(bytes32,address,bool)": FunctionFragment;
    "deployApp(bytes32,address,bytes)": FunctionFragment;
    "getAppAddress(bytes32)": FunctionFragment;
    "resetApp(bytes32,address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "connectApp",
    values: [BytesLike, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "deployApp",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetApp",
    values: [BytesLike, string, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "connectApp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deployApp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAppAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resetApp", data: BytesLike): Result;

  events: {};
}

export interface IAppManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAppManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    connectApp(
      id: BytesLike,
      appAddress: string,
      isNative: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployApp(
      id: BytesLike,
      appCode: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAppAddress(id: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    resetApp(
      id: BytesLike,
      appAddress: string,
      isNative: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  connectApp(
    id: BytesLike,
    appAddress: string,
    isNative: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployApp(
    id: BytesLike,
    appCode: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAppAddress(id: BytesLike, overrides?: CallOverrides): Promise<string>;

  resetApp(
    id: BytesLike,
    appAddress: string,
    isNative: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    connectApp(
      id: BytesLike,
      appAddress: string,
      isNative: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    deployApp(
      id: BytesLike,
      appCode: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getAppAddress(id: BytesLike, overrides?: CallOverrides): Promise<string>;

    resetApp(
      id: BytesLike,
      appAddress: string,
      isNative: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    connectApp(
      id: BytesLike,
      appAddress: string,
      isNative: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployApp(
      id: BytesLike,
      appCode: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAppAddress(id: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    resetApp(
      id: BytesLike,
      appAddress: string,
      isNative: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    connectApp(
      id: BytesLike,
      appAddress: string,
      isNative: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployApp(
      id: BytesLike,
      appCode: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAppAddress(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    resetApp(
      id: BytesLike,
      appAddress: string,
      isNative: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
