/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IUpdateManagerInterface extends utils.Interface {
  functions: {
    "getAppCodeHistory(bytes32)": FunctionFragment;
    "getLastAppCode(bytes32)": FunctionFragment;
    "setAppCode(bytes32,address)": FunctionFragment;
    "upgrade(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAppCodeHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastAppCode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAppCode",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "upgrade", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "getAppCodeHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastAppCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAppCode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;

  events: {};
}

export interface IUpdateManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IUpdateManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAppCodeHistory(
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getLastAppCode(
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setAppCode(
      app: BytesLike,
      code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgrade(
      appCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAppCodeHistory(
    app: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getLastAppCode(app: BytesLike, overrides?: CallOverrides): Promise<string>;

  setAppCode(
    app: BytesLike,
    code: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgrade(
    appCode: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAppCodeHistory(
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getLastAppCode(app: BytesLike, overrides?: CallOverrides): Promise<string>;

    setAppCode(
      app: BytesLike,
      code: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgrade(appCode: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getAppCodeHistory(
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastAppCode(
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAppCode(
      app: BytesLike,
      code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgrade(
      appCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAppCodeHistory(
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLastAppCode(
      app: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAppCode(
      app: BytesLike,
      code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgrade(
      appCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
