/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Gap50, Gap50Interface } from "../Gap50";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
];

export class Gap50__factory {
  static readonly abi = _abi;
  static createInterface(): Gap50Interface {
    return new utils.Interface(_abi) as Gap50Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Gap50 {
    return new Contract(address, _abi, signerOrProvider) as Gap50;
  }
}
