/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAdminController,
  IAdminControllerInterface,
} from "../IAdminController";

const _abi = [
  {
    inputs: [],
    name: "creator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAdminController__factory {
  static readonly abi = _abi;
  static createInterface(): IAdminControllerInterface {
    return new utils.Interface(_abi) as IAdminControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAdminController {
    return new Contract(address, _abi, signerOrProvider) as IAdminController;
  }
}
