/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAppManager, IAppManagerInterface } from "../IAppManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "appAddress",
        type: "address",
      },
      {
        internalType: "bool",
        name: "isNative",
        type: "bool",
      },
    ],
    name: "connectApp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "appCode",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "deployApp",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "getAppAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "appAddress",
        type: "address",
      },
      {
        internalType: "bool",
        name: "isNative",
        type: "bool",
      },
    ],
    name: "resetApp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAppManager__factory {
  static readonly abi = _abi;
  static createInterface(): IAppManagerInterface {
    return new utils.Interface(_abi) as IAppManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAppManager {
    return new Contract(address, _abi, signerOrProvider) as IAppManager;
  }
}
