/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISafeFactory, ISafeFactoryInterface } from "../ISafeFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_singleton",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "initializer",
        type: "bytes",
      },
    ],
    name: "createProxy",
    outputs: [
      {
        internalType: "contract ISafe",
        name: "proxy",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISafeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeFactoryInterface {
    return new utils.Interface(_abi) as ISafeFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISafeFactory {
    return new Contract(address, _abi, signerOrProvider) as ISafeFactory;
  }
}
