/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { WithSemver, WithSemverInterface } from "../WithSemver";

const _abi = [
  {
    inputs: [],
    name: "__semver",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class WithSemver__factory {
  static readonly abi = _abi;
  static createInterface(): WithSemverInterface {
    return new utils.Interface(_abi) as WithSemverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WithSemver {
    return new Contract(address, _abi, signerOrProvider) as WithSemver;
  }
}
