export enum MetamaskErrorCode {
	CHAIN_HAS_NOT_BEEN_ADDED = 4902,
	USER_REJECTED_THE_REQUEST = 4001
}
export enum ContractErrorCode {
	INVALID_INITIALIZATION_ERROR = 'INITIALIZATION',
	INVALID_AUTHORIZATION_ERROR = 'AUTHORIZATION',
	INVARIANT_ERROR = 'INVARIANT',
	VALIDATION_ERROR = 'VALIDATION',
	UNAVAILABLE_ERROR = 'UNAVAILABLE',
	NOT_ACTIVE_ERROR = 'NOT_ACTIVE',
	NO_TREASURY_ADDRESS = 'NO_TREASURY_ADDRESS',
	APP_WAS_INITED_ERROR = 'APP_WAS_INITED',
	ILLEGAL_ADDRESS = 'ADDRESS_ASSOCIATES_WITH_APP',
	BUY_LIMIT_ERROR = 'BUY_LIMIT_ERROR',
	NULL_STABLECOIN_ADDRESS = 'NULL_STABLECOIN_ADDRESS',
	UNSUPPORTED_TOKEN_ADDRESS = 'UNSUPPORTED_TOKEN_ADDRESS',
	NOT_FOUND_PRICE_FOR_TIER = 'NOT_FOUND_PRICE_FOR_TIER',
	INSUFFICIENT_AMOUNTS_OF_FUNDS = 'INSUFFICIENT_AMOUNTS_OF_FUNDS',
	INSUFFICIENT_ALLOWANCE = 'INSUFFICIENT_ALLOWANCE',
	BASIC_TOKEN_ADDRESS_NOT_SET = 'BASIC_TOKEN_ADDRESS_NOT_SET'
}
